"""add observable sync progress

Revision ID: 0ca575a6c1ad
Revises: dff6ecaf942c
Create Date: 2026-09-05 13:43:14.056780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca575a6c1ad'
down_revision: Union[str, Sequence[str], None] = 'dff6ecaf942c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_batch_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sync_job_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_batch_logs_sync_job_id'), 'sync_batch_logs', ['sync_job_id'], unique=False)
    op.add_column(
    'sync_jobs',
    sa.Column(
        'current_stage',
        sa.String(length=30),
        nullable=True,
    ),
)

op.add_column(
    'sync_jobs',
    sa.Column(
        'total_items',
        sa.Integer(),
        nullable=False,
        server_default='0',
    ),
)

op.add_column(
    'sync_jobs',
    sa.Column(
        'processed_items',
        sa.Integer(),
        nullable=False,
        server_default='0',
    ),
)

op.add_column(
    'sync_jobs',
    sa.Column(
        'total_batches',
        sa.Integer(),
        nullable=False,
        server_default='0',
    ),
)

op.add_column(
    'sync_jobs',
    sa.Column(
        'completed_batches',
        sa.Integer(),
        nullable=False,
        server_default='0',
    ),
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_jobs', 'completed_batches')
    op.drop_column('sync_jobs', 'total_batches')
    op.drop_column('sync_jobs', 'processed_items')
    op.drop_column('sync_jobs', 'total_items')
    op.drop_column('sync_jobs', 'current_stage')
    op.drop_index(op.f('ix_sync_batch_logs_sync_job_id'), table_name='sync_batch_logs')
    op.drop_table('sync_batch_logs')
    # ### end Alembic commands ###
