"""create feedback table

Revision ID: 78dcbfed845c
Revises: 48bd8f81af77
Create Date: 2026-08-27 20:41:11.088478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78dcbfed845c'
down_revision: Union[str, Sequence[str], None] = '48bd8f81af77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('source_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='processing_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['feedback_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_feedback_source_external_id')
    )
    op.create_index(op.f('ix_feedback_processing_status'), 'feedback', ['processing_status'], unique=False)
    op.create_index(op.f('ix_feedback_project_id'), 'feedback', ['project_id'], unique=False)
    op.create_index(op.f('ix_feedback_source_id'), 'feedback', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_source_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_project_id'), table_name='feedback')
    op.drop_index(op.f('ix_feedback_processing_status'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###
