"""add feedback analysis

Revision ID: b44f129ea4e6
Revises: 78dcbfed845c
Create Date: 2026-08-28 12:34:35.787777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44f129ea4e6'
down_revision: Union[str, Sequence[str], None] = '78dcbfed845c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='feedback_sentiment'), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('pain_point', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='feedback_severity'), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('analysis_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_analysis_feedback_id'), 'feedback_analysis', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    op.drop_index(
        op.f("ix_feedback_analysis_feedback_id"),
        table_name="feedback_analysis",
    )

    op.drop_table("feedback_analysis")

    sa.Enum(
        name="analysis_status"
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name="feedback_severity"
    ).drop(op.get_bind(), checkfirst=True)

    sa.Enum(
        name="feedback_sentiment"
    ).drop(op.get_bind(), checkfirst=True)